version: "3"

services:

  wordpress:
    image: caspianlabs/wordpress-xdebug:latest
    restart: always
    env_file:
      - .env
    environment:
        WORDPRESS_DB_PASSWORD: wordpress
        XDEBUG_CONFIG: remote_host="${HOST_IP}"
    ports:
        - "8080:80"
    volumes:
      - "./html:/var/www/html"
      - "./wp-content:/var/www/html/wp-content"
    depends_on:
        - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: wordpress
        MYSQL_DATABASE: wordpress
    ports:
        - "13306:3306"
    volumes:
        - "./mysql:/var/lib/mysql"

